### ISSUE TITLE
What is the "positioning" of the did-methods Working Group?

### ISSUE THREAD

**Issue by mwherman2000** [decentralized-identity/did-methods#8]
For example (these are intended to be independent questions/axis):

1. Is/was the WG positioned to be "outside" the traditional SDOs? ...e.g. W3C, DIF, IETF, ToIP, ... My assumption: yes
2. Who is the "host" organization? ...e.g. who is hosting the repository, zoom calls, etc. My assumption: DIF
3. Which governance structures is the WG expected to use? ...e.g. processes, Code of Conduct, etc. My assumption: the WG is free to decide - some by WG/parent circle consensus, others by DID Method cluster circle members
4. Ultimately, the specifications need to be ratified by one or more SDOs. Which one(s)? My assumption: it will vary DID Method (cluster) by DID Method (cluster) based on the needs/descretion of the method controllers and circle members for each particular cluster of DID Methods 

Cc: @peacekeeper

**Comment by kimdhamilton** [comment]
Accidental close; re-opened in case any questions.
